name: qurity
description: "تطبيق قرية أبوديشيشة - التطبيق المجتمعي لخدمة قرى المنطقة"
publish_to: 'none'

version: 3.1.1+0

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.11.0
  cloud_firestore: ^6.6.0
  google_sign_in: 6.3.0
  firebase_auth: ^6.5.4
  firebase_auth_web: any
  firebase_storage: ^13.4.3
  firebase_storage_web: any
  firebase_messaging: ^16.4.1
  image_picker: ^1.2.2
  http: ^1.0.0
  url_launcher: ^6.0.0
  share_plus: ^13.2.0
  shared_preferences: ^2.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.0.0
  smooth_page_indicator: ^2.0.1
  flutter_animate: ^4.0.0
  google_fonts: ^8.1.0
  flutter_slidable: ^4.0.3
  pull_to_refresh_flutter3: ^2.0.0
  flutter_rating_bar: ^4.0.0
  skeletonizer: ^2.1.3
  confetti: ^0.8.0
  liquid_pull_to_refresh: ^3.0.0
  animated_text_kit: ^4.2.0
  flutter_carousel_widget: ^3.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/market/
    - assets/animations/
    - assets/images/
    - assets/images/Qurity.png