/// 📚 بيانات الحروف العربية — 28 حرفًا بأشكالها الأربعة وكلمة مثال وإيموجي.
class ArabicLetter {
  const ArabicLetter({
    required this.letter,
    required this.name,
    required this.isolated,
    required this.initial,
    required this.medial,
    required this.finalForm,
    required this.word,
    required this.emoji,
    required this.image,
    required this.colorIndex,
  });

  final String letter;
  final String name;
  final String isolated;
  final String initial;
  final String medial;
  final String finalForm;
  final String word;
  final String emoji;

  /// مسار صورة توضيحية داخل الأصول (معبّرة عن كلمة المثال).
  final String image;
  final int colorIndex;
}

const List<ArabicLetter> kArabicLetters = [
  ArabicLetter(
      letter: 'أ',
      name: 'ألف',
      isolated: 'ا',
      initial: 'ا',
      medial: 'ـا',
      finalForm: 'ـا',
      word: 'أَسَد',
      emoji: '🦁',
      colorIndex: 0,
      image: 'assets/images/letters/l01.jpg'),
  ArabicLetter(
      letter: 'ب',
      name: 'باء',
      isolated: 'ب',
      initial: 'بـ',
      medial: 'ـبـ',
      finalForm: 'ـب',
      word: 'بَطَّة',
      emoji: '🦆',
      colorIndex: 1,
      image: 'assets/images/letters/l02.jpg'),
  ArabicLetter(
      letter: 'ت',
      name: 'تاء',
      isolated: 'ت',
      initial: 'تـ',
      medial: 'ـتـ',
      finalForm: 'ـت',
      word: 'تُفَّاح',
      emoji: '🍎',
      colorIndex: 2,
      image: 'assets/images/letters/l03.jpg'),
  ArabicLetter(
      letter: 'ث',
      name: 'ثاء',
      isolated: 'ث',
      initial: 'ثـ',
      medial: 'ـثـ',
      finalForm: 'ـث',
      word: 'ثُعْبان',
      emoji: '🐍',
      colorIndex: 3,
      image: 'assets/images/letters/l04.jpg'),
  ArabicLetter(
      letter: 'ج',
      name: 'جيم',
      isolated: 'ج',
      initial: 'جـ',
      medial: 'ـجـ',
      finalForm: 'ـج',
      word: 'جَمَل',
      emoji: '🐪',
      colorIndex: 4,
      image: 'assets/images/letters/l05.jpg'),
  ArabicLetter(
      letter: 'ح',
      name: 'حاء',
      isolated: 'ح',
      initial: 'حـ',
      medial: 'ـحـ',
      finalForm: 'ـح',
      word: 'حِصان',
      emoji: '🐴',
      colorIndex: 5,
      image: 'assets/images/letters/l06.jpg'),
  ArabicLetter(
      letter: 'خ',
      name: 'خاء',
      isolated: 'خ',
      initial: 'خـ',
      medial: 'ـخـ',
      finalForm: 'ـخ',
      word: 'خَروف',
      emoji: '🐑',
      colorIndex: 6,
      image: 'assets/images/letters/l07.jpg'),
  ArabicLetter(
      letter: 'د',
      name: 'دال',
      isolated: 'د',
      initial: 'د',
      medial: 'ـد',
      finalForm: 'ـد',
      word: 'دُبّ',
      emoji: '🐻',
      colorIndex: 7,
      image: 'assets/images/letters/l08.jpg'),
  ArabicLetter(
      letter: 'ذ',
      name: 'ذال',
      isolated: 'ذ',
      initial: 'ذ',
      medial: 'ـذ',
      finalForm: 'ـذ',
      word: 'ذُرَة',
      emoji: '🌽',
      colorIndex: 8,
      image: 'assets/images/letters/l09.jpg'),
  ArabicLetter(
      letter: 'ر',
      name: 'راء',
      isolated: 'ر',
      initial: 'ر',
      medial: 'ـر',
      finalForm: 'ـر',
      word: 'رِيشة',
      emoji: '🪶',
      colorIndex: 9,
      image: 'assets/images/letters/l10.jpg'),
  ArabicLetter(
      letter: 'ز',
      name: 'زاي',
      isolated: 'ز',
      initial: 'ز',
      medial: 'ـز',
      finalForm: 'ـز',
      word: 'زَرافة',
      emoji: '🦒',
      colorIndex: 10,
      image: 'assets/images/letters/l11.jpg'),
  ArabicLetter(
      letter: 'س',
      name: 'سين',
      isolated: 'س',
      initial: 'سـ',
      medial: 'ـسـ',
      finalForm: 'ـس',
      word: 'سَمَكة',
      emoji: '🐟',
      colorIndex: 11,
      image: 'assets/images/letters/l12.jpg'),
  ArabicLetter(
      letter: 'ش',
      name: 'شين',
      isolated: 'ش',
      initial: 'شـ',
      medial: 'ـشـ',
      finalForm: 'ـش',
      word: 'شَمْس',
      emoji: '☀️',
      colorIndex: 12,
      image: 'assets/images/letters/l13.jpg'),
  ArabicLetter(
      letter: 'ص',
      name: 'صاد',
      isolated: 'ص',
      initial: 'صـ',
      medial: 'ـصـ',
      finalForm: 'ـص',
      word: 'صَقْر',
      emoji: '🦅',
      colorIndex: 13,
      image: 'assets/images/letters/l14.jpg'),
  ArabicLetter(
      letter: 'ض',
      name: 'ضاد',
      isolated: 'ض',
      initial: 'ضـ',
      medial: 'ـضـ',
      finalForm: 'ـض',
      word: 'ضِفْدَع',
      emoji: '🐸',
      colorIndex: 14,
      image: 'assets/images/letters/l15.jpg'),
  ArabicLetter(
      letter: 'ط',
      name: 'طاء',
      isolated: 'ط',
      initial: 'طـ',
      medial: 'ـطـ',
      finalForm: 'ـط',
      word: 'طائِرة',
      emoji: '✈️',
      colorIndex: 15,
      image: 'assets/images/letters/l16.jpg'),
  ArabicLetter(
      letter: 'ظ',
      name: 'ظاء',
      isolated: 'ظ',
      initial: 'ظـ',
      medial: 'ـظـ',
      finalForm: 'ـظ',
      word: 'ظَرْف',
      emoji: '✉️',
      colorIndex: 16,
      image: 'assets/images/letters/l17.jpg'),
  ArabicLetter(
      letter: 'ع',
      name: 'عين',
      isolated: 'ع',
      initial: 'عـ',
      medial: 'ـعـ',
      finalForm: 'ـع',
      word: 'عِنَب',
      emoji: '🍇',
      colorIndex: 17,
      image: 'assets/images/letters/l18.jpg'),
  ArabicLetter(
      letter: 'غ',
      name: 'غين',
      isolated: 'غ',
      initial: 'غـ',
      medial: 'ـغـ',
      finalForm: 'ـغ',
      word: 'غُراب',
      emoji: '🐦',
      colorIndex: 18,
      image: 'assets/images/letters/l19.jpg'),
  ArabicLetter(
      letter: 'ف',
      name: 'فاء',
      isolated: 'ف',
      initial: 'فـ',
      medial: 'ـفـ',
      finalForm: 'ـف',
      word: 'فِيل',
      emoji: '🐘',
      colorIndex: 19,
      image: 'assets/images/letters/l20.jpg'),
  ArabicLetter(
      letter: 'ق',
      name: 'قاف',
      isolated: 'ق',
      initial: 'قـ',
      medial: 'ـقـ',
      finalForm: 'ـق',
      word: 'قِطّة',
      emoji: '🐱',
      colorIndex: 20,
      image: 'assets/images/letters/l21.jpg'),
  ArabicLetter(
      letter: 'ك',
      name: 'كاف',
      isolated: 'ك',
      initial: 'كـ',
      medial: 'ـكـ',
      finalForm: 'ـك',
      word: 'كُرة',
      emoji: '⚽',
      colorIndex: 21,
      image: 'assets/images/letters/l22.jpg'),
  ArabicLetter(
      letter: 'ل',
      name: 'لام',
      isolated: 'ل',
      initial: 'لـ',
      medial: 'ـلـ',
      finalForm: 'ـل',
      word: 'لَيْمون',
      emoji: '🍋',
      colorIndex: 22,
      image: 'assets/images/letters/l23.jpg'),
  ArabicLetter(
      letter: 'م',
      name: 'ميم',
      isolated: 'م',
      initial: 'مـ',
      medial: 'ـمـ',
      finalForm: 'ـم',
      word: 'مَوْز',
      emoji: '🍌',
      colorIndex: 23,
      image: 'assets/images/letters/l24.jpg'),
  ArabicLetter(
      letter: 'ن',
      name: 'نون',
      isolated: 'ن',
      initial: 'نـ',
      medial: 'ـنـ',
      finalForm: 'ـن',
      word: 'نَجْمة',
      emoji: '⭐',
      colorIndex: 24,
      image: 'assets/images/letters/l25.jpg'),
  ArabicLetter(
      letter: 'ه',
      name: 'هاء',
      isolated: 'ه',
      initial: 'هـ',
      medial: 'ـهـ',
      finalForm: 'ـه',
      word: 'هِلال',
      emoji: '🌙',
      colorIndex: 25,
      image: 'assets/images/letters/l26.jpg'),
  ArabicLetter(
      letter: 'و',
      name: 'واو',
      isolated: 'و',
      initial: 'و',
      medial: 'ـو',
      finalForm: 'ـو',
      word: 'وَرْدَة',
      emoji: '🌹',
      colorIndex: 26,
      image: 'assets/images/letters/l27.jpg'),
  ArabicLetter(
      letter: 'ي',
      name: 'ياء',
      isolated: 'ي',
      initial: 'يـ',
      medial: 'ـيـ',
      finalForm: 'ـي',
      word: 'يَد',
      emoji: '✋',
      colorIndex: 27,
      image: 'assets/images/letters/l28.jpg'),
];
